import re

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# English replacements
en_replacements = {
    'lang="vi"': 'lang="en"',
    'Hiro Barbershop | Premium Barbershop &amp; Men\'s Grooming in HCMC': 'Hiro Barbershop | Premium Barbershop & Men\'s Grooming in HCMC',
    'Đẳng cấp kiểu tóc nam hiện đại': "Modern men's grooming excellence",
    'Fade chuẩn form': "Perfect fade",
    'phục vụ tận tâm': "dedicated service",
    'Trải nghiệm không gian cắt tóc nam cao cấp tại trung tâm Quận 1. Nơi các nghệ nhân tạo nên phong thái lịch lãm cho từng quý ông.': "Experience a premium barbershop in the heart of District 1. Where master barbers craft elegant styles for every gentleman.",
    'từ hơn 500+ quý ông': "from over 500+ gentlemen",
    'Tại sao chọn Hiro Barbershop': "Why choose Hiro Barbershop",
    'CHUYÊN NGHIỆP': "PROFESSIONAL",
    'Từng đường kéo được thực hiện bởi những nghệ nhân hàng đầu, đảm bảo độ chính xác tuyệt đối.': "Every cut is performed by top artisans, ensuring absolute precision.",
    'ĐÚNG GIỜ': "ON TIME",
    'Sự tôn trọng thời gian của quý ông là ưu tiên tuyệt đối. Đặt lịch là làm ngay.': "Respecting a gentleman's time is our absolute priority. Bookings are honored instantly.",
    'PHONG CÁCH': "STYLE",
    'Luôn cập nhật những xu hướng tóc nam thịnh hành nhất, tư vấn phù hợp khuôn mặt.': "Always updated with the latest men's hair trends, tailored to your face shape.",
    'DỊCH VỤ VIP': "VIP SERVICE",
    'Không gian riêng tư, thư giãn cùng đồ uống hảo hạng trong suốt quá trình trải nghiệm.': "Private, relaxing atmosphere with premium drinks during your experience.",
    'DỊCH VỤ ĐẲNG CẤP': "PREMIUM SERVICES",
    'Chúng tôi không chỉ cắt tóc, chúng tôi kiến tạo phong thái của một quý ông hiện đại thông qua những kỹ thuật tinh xảo nhất.': "We don't just cut hair; we craft the demeanor of a modern gentleman through refined techniques.",
    'Cắt tỉa nghệ thuật': "Artistic Trim",
    'Tư vấn kiểu tóc phù hợp với khuôn mặt và phong cách cá nhân.': "Consultation for a hairstyle that fits your face and personal style.",
    'GỘI ĐẦU THƯ GIÃN': "RELAXING WASH",
    'TẠO KIỂU CAO CẤP': "PREMIUM STYLING",
    'Fade Chuyên Sâu': "Deep Fade",
    'Kỹ thuật Fade sắc nét, chuyển màu mượt mà chuẩn quốc tế, tạo hiệu ứng thị giác ấn tượng.': "Sharp, internationally-standardized fade techniques with smooth transitions.",
    'Uốn Texture / Sidepart': "Texture / Sidepart Perm",
    'Sử dụng thuốc uốn organic cao cấp bảo vệ tóc tối ưu, tạo nếp tự nhiên và bồng bềnh lâu dài.': "Using premium organic perm solutions for natural waves and long-lasting volume.",
    'Cạo mặt truyền thống': "Traditional Shave",
    'Liệu trình cạo mặt bằng dao cạo chuẩn, kết hợp đắp khăn nóng và massage thư giãn vùng mặt.': "Traditional straight razor shave, complete with a hot towel and relaxing facial massage.",
    'Trải nghiệm toàn diện: Cắt + Fade + Cạo mặt truyền thống + Chăm sóc da mặt chuyên sâu. Lựa chọn hoàn hảo cho quý ông trước những sự kiện quan trọng.': "The complete experience: Cut + Fade + Traditional Shave + Deep Facial Care. The perfect choice before important events.",
    'TÁC PHẨM CỦA CHÚNG TÔI': "OUR MASTERPIECES",
    'ĐỘI NGŨ NGHỆ NHÂN': "MASTER BARBERS",
    'Những đôi tay vàng đằng sau những tuyệt tác kiểu tóc. Đội ngũ của chúng tôi liên tục tu nghiệp và cập nhật xu hướng.': "The golden hands behind every masterpiece. Our team continuously trains to master the latest trends.",
    'ĐẶT LỊCH HẸN': "MAKE A RESERVATION",
    'Họ và tên': "Full Name",
    'HỌ VÀ TÊN': "FULL NAME",
    'Số điện thoại': "Phone Number",
    'SỐ ĐIỆN THOẠI': "PHONE NUMBER",
    'CHỌN DỊCH VỤ': "SELECT SERVICE",
    'COMBO HIRO BARBERSHOP': "HIRO BARBERSHOP COMBO",
    'FADE CHUYÊN SÂU': "DEEP FADE",
    'CẮT TỈA NGHỆ THUẬT': "ARTISTIC TRIM",
    'UỐN TEXTURE / SIDEPART': "TEXTURE / SIDEPART PERM",
    'CHỌN GIỜ (HÔM NAY)': "SELECT TIME (TODAY)",
    'Đã kín lịch': "Fully booked",
    'XÁC NHẬN ĐẶT LỊCH': "CONFIRM BOOKING",
    'Địa chỉ': "Address",
    'SĐT: +420 777 882 999': "Tel: +420 777 882 999",
    'Giờ mở cửa': "Opening Hours",
    'Thứ 2 - Thứ 6: 09:30 - 20:00': "Mon - Fri: 09:30 - 20:00",
    'Thứ 7: 09:30 - 19:00': "Sat: 09:30 - 19:00",
    'CN: 10:00 - 12:30': "Sun: 10:00 - 12:30",
    'Chính thức khai trương và đi vào hoạt động từ tháng 11 năm 2024, cùng với sức trẻ sáng tạo và kinh nghiệm tích lũy nhiều năm. Hiro Barbershop hy vọng sẽ trở thành một người bạn giúp định hình phong cách cho khách hàng, giúp bạn thể hiện cá tính riêng nhưng vẫn phù hợp với công việc và cuộc sống hàng ngày. Với gần 150 đánh giá tích cực trên Google Maps cùng mức giá hợp lý, dễ tiếp cận, Hiro Barbershop là một thương hiệu mới rất đáng để trải nghiệm ❤️❤️❤️❤️': "Officially opening and starting operations in November 2024, along with the creativity of youth and experience gathered over many years. Hiro Barbershop hopes to become a friend that helps shape the style for customers, allowing you to express your personality while still being suitable for work and daily life. With nearly 150 positive reviews on Google Maps and reasonable, accessible prices, Hiro Barbershop is a new brand worth experiencing ❤️❤️❤️❤️",
    'LIÊN KẾT': "LINKS",
    'Dịch vụ': "Services",
    'Thư viện ảnh': "Gallery",
    'Đội ngũ': "Team",
    'Chính sách bảo mật': "Privacy Policy",
    'BẢN TIN': "NEWSLETTER",
    'Đăng ký để nhận ưu đãi và mẹo chăm sóc tóc độc quyền.': "Subscribe for exclusive offers and grooming tips.",
    'Email của bạn': "Your Email",
    'Đăng ký': "Subscribe",
}

en_html = html
for k, v in en_replacements.items():
    en_html = en_html.replace(k, v)

with open('en.html', 'w', encoding='utf-8') as f:
    f.write(en_html)

cs_replacements = {
    'lang="vi"': 'lang="cs"',
    'Đẳng cấp kiểu tóc nam hiện đại': "Moderní pánská péče",
    'Fade chuẩn form': "Dokonalý fade",
    'phục vụ tận tâm': "oddaný servis",
    'Trải nghiệm không gian cắt tóc nam cao cấp tại trung tâm Quận 1. Nơi các nghệ nhân tạo nên phong thái lịch lãm cho từng quý ông.': "Zažijte prémiové holičství v srdci District 1. Kde mistři holiči tvoří elegantní styl pro každého gentlemana.",
    'từ hơn 500+ quý ông': "od více než 500 gentlemanů",
    'Tại sao chọn Hiro Barbershop': "Proč si vybrat Hiro Barbershop",
    'CHUYÊN NGHIỆP': "PROFESIONÁLNÍ",
    'Từng đường kéo được thực hiện bởi những nghệ nhân hàng đầu, đảm bảo độ chính xác tuyệt đối.': "Každý střih provádějí špičkoví řemeslníci, zaručující absolutní přesnost.",
    'ĐÚNG GIỜ': "NA ČAS",
    'Sự tôn trọng thời gian của quý ông là ưu tiên tuyệt đối. Đặt lịch là làm ngay.': "Respektování času gentlemana je naší absolutní prioritou.",
    'PHONG CÁCH': "STYL",
    'Luôn cập nhật những xu hướng tóc nam thịnh hành nhất, tư vấn phù hợp khuôn mặt.': "Neustále sledujeme nejnovější trendy v pánských účesech.",
    'DỊCH VỤ VIP': "VIP SLUŽBY",
    'Không gian riêng tư, thư giãn cùng đồ uống hảo hạng trong suốt quá trình trải nghiệm.': "Soukromá, relaxační atmosféra s prémiovými nápoji během vašeho zážitku.",
    'DỊCH VỤ ĐẲNG CẤP': "PRÉMIOVÉ SLUŽBY",
    'Chúng tôi không chỉ cắt tóc, chúng tôi kiến tạo phong thái của một quý ông hiện đại thông qua những kỹ thuật tinh xảo nhất.': "Nejen že stříháme vlasy; vytváříme styl moderního gentlemana skrze vytříbené techniky.",
    'Cắt tỉa nghệ thuật': "Umělecký Střih",
    'Tư vấn kiểu tóc phù hợp với khuôn mặt và phong cách cá nhân.': "Konzultace účesu na míru vašemu obličeji a osobnímu stylu.",
    'GỘI ĐẦU THƯ GIÃN': "RELAXAČNÍ MYTÍ",
    'TẠO KIỂU CAO CẤP': "PRÉMIOVÝ STYLING",
    'Fade Chuyên Sâu': "Dokonalý Fade",
    'Kỹ thuật Fade sắc nét, chuyển màu mượt mà chuẩn quốc tế, tạo hiệu ứng thị giác ấn tượng.': "Ostré, mezinárodně standardizované fade techniky s plynulými přechody.",
    'Uốn Texture / Sidepart': "Trvalá Texture / Sidepart",
    'Sử dụng thuốc uốn organic cao cấp bảo vệ tóc tối ưu, tạo nếp tự nhiên và bồng bềnh lâu dài.': "Používáme prémiové organické přípravky pro přirozené vlny a dlouhotrvající objem.",
    'Cạo mặt truyền thống': "Tradiční Holení",
    'Liệu trình cạo mặt bằng dao cạo chuẩn, kết hợp đắp khăn nóng và massage thư giãn vùng mặt.': "Tradiční holení břitvou, kompletní s horkým ručníkem a relaxační masáží obličeje.",
    'Trải nghiệm toàn diện: Cắt + Fade + Cạo mặt truyền thống + Chăm sóc da mặt chuyên sâu. Lựa chọn hoàn hảo cho quý ông trước những sự kiện quan trọng.': "Kompletní zážitek: Střih + Fade + Tradiční Holení + Hloubková Péče o Pleť. Dokonalá volba před důležitými událostmi.",
    'TÁC PHẨM CỦA CHÚNG TÔI': "NAŠE MISTROVSKÁ DÍLA",
    'ĐỘI NGŨ NGHỆ NHÂN': "MISTŘI HOLIČI",
    'Những đôi tay vàng đằng sau những tuyệt tác kiểu tóc. Đội ngũ của chúng tôi liên tục tu nghiệp và cập nhật xu hướng.': "Zlaté ruce za každým mistrovským dílem. Náš tým se neustále školí.",
    'ĐẶT LỊCH HẸN': "REZERVACE",
    'Họ và tên': "Jméno a příjmení",
    'HỌ VÀ TÊN': "JMÉNO A PŘÍJMENÍ",
    'Số điện thoại': "Telefonní číslo",
    'SỐ ĐIỆN THOẠI': "TELEFONNÍ ČÍSLO",
    'CHỌN DỊCH VỤ': "VYBERTE SLUŽBU",
    'COMBO HIRO BARBERSHOP': "HIRO BARBERSHOP BALÍČEK",
    'FADE CHUYÊN SÂU': "DOKONALÝ FADE",
    'CẮT TỈA NGHỆ THUẬT': "UMĚLECKÝ STŘIH",
    'UỐN TEXTURE / SIDEPART': "TRVALÁ TEXTURE",
    'CHỌN GIỜ (HÔM NAY)': "VYBERTE ČAS (DNES)",
    'Đã kín lịch': "Plně obsazeno",
    'XÁC NHẬN ĐẶT LỊCH': "POTVRDIT REZERVACI",
    'Địa chỉ': "Adresa",
    'SĐT: +420 777 882 999': "Tel: +420 777 882 999",
    'Giờ mở cửa': "Otevírací Doba",
    'Thứ 2 - Thứ 6: 09:30 - 20:00': "Po - Pá: 09:30 - 20:00",
    'Thứ 7: 09:30 - 19:00': "So: 09:30 - 19:00",
    'CN: 10:00 - 12:30': "Ne: 10:00 - 12:30",
    'Nơi truyền thống kết hợp cùng sự tỉ mỉ hiện đại. Nâng tầm chuẩn mực chăm sóc sắc đẹp nam giới tại trung tâm Sài Gòn từ 2018.': "Oficiálně otevíráme a zahajujeme provoz v listopadu 2024, s mladistvou kreativitou a zkušenostmi nasbíranými za mnoho let. Hiro Barbershop doufá, že se stane přítelem, který zákazníkům pomůže utvářet styl, umožní vám vyjádřit vaši osobnost, a přitom zůstane vhodný pro práci i každodenní život. S téměř 150 pozitivními recenzemi na Google Maps a rozumnými, dostupnými cenami je Hiro Barbershop novou značkou, kterou stojí za to vyzkoušet ❤️❤️❤️❤️",
    'LIÊN KẾT': "ODKAZY",
    'Dịch vụ': "Služby",
    'Thư viện ảnh': "Galerie",
    'Đội ngũ': "Tým",
    'Chính sách bảo mật': "Zásady ochrany osobních údajů",
    'BẢN TIN': "NEWSLETTER",
    'Đăng ký để nhận ưu đãi và mẹo chăm sóc tóc độc quyền.': "Přihlaste se k odběru pro exkluzivní nabídky a tipy na péči.",
    'Email của bạn': "Váš Email",
    'Đăng ký': "Odebírat",
}

cs_html = html
for k, v in cs_replacements.items():
    cs_html = cs_html.replace(k, v)

with open('cs.html', 'w', encoding='utf-8') as f:
    f.write(cs_html)
